version: '3.4'

#Creates a Docker swarm for nats-streaming-server:
#REeference: https://docs.nats.io/nats-streaming-server/swarm

networks:
  nats-streaming-example:
    attachable: true
    driver: overlay

services:
  nats-cluster-node-A:
    image: nats:latest
    restart: always
    command: "-cluster nats://0.0.0.0:6222 -routes nats://nats-cluster-node-A:6222,nats://nats-cluster-node-B:6222,nats://nats-cluster-node-C:6222"
    networks:
      - nats-streaming-example

  nats-cluster-node-B:
    image: nats:latest
    restart: always
    command: "-cluster nats://0.0.0.0:6222 -routes nats://nats-cluster-node-A:6222,nats://nats-cluster-node-B:6222,nats://nats-cluster-node-C:6222"
    networks:
      - nats-streaming-example

  nats-cluster-node-C:
    image: nats:latest
    restart: always
    command: "-cluster nats://0.0.0.0:6222 -routes nats://nats-cluster-node-A:6222,nats://nats-cluster-node-B:6222,nats://nats-cluster-node-C:6222"
    networks:
      - nats-streaming-example

  nats-streaming-node-A:
    image: nats-streaming:latest
    restart: always
    expose:
      - "4222"
      - "8222"
      - "6221"
    ports:
      - "4222"
      - "8222"
      - "6221:6221"
    hostname: "nats-node-A"
    volumes:
      - "./logs:/logs"
      - "./nats/shareddatastore-A:/nats/shareddatastore-A"
      - "./nats/cluster/nats-cluster-node-A:/cluster/nats-cluster-node-A"
    command: "-p 4222 -store file -dir /nats/shareddatastore-A -clustered -cluster_id swarm -cluster_node_id node-A -cluster_log_path /cluster/nats-cluster-node-A -cluster_peers node-A,node-B,node-C -nats_server nats://nats-cluster-node-A:4222,nats://nats-cluster-node-B:4222,nats://nats-cluster-node-C:4222 -l ./logs/nats-node-A.log -DV"
    networks:
      - nats-streaming-example

  nats-streaming-node-B:
    image: nats-streaming:latest
    restart: always
    expose:
      - "4222"
      - "6222"
    ports:
      - "4222"
      - "6222:6222"
    hostname: "nats-node-B"
    volumes:
      - "./logs:/logs"
      - "./nats/shareddatastore-B:/nats/shareddatastore-B"
      - "./nats/cluster/nats-cluster-node-B:/cluster/nats-cluster-node-B"
    command: "-p 4222 -store file -dir /nats/shareddatastore-B -clustered -cluster_id swarm -cluster_node_id node-B -cluster_log_path /cluster/nats-cluster-node-B -cluster_peers node-A,node-B,node-C -nats_server nats://nats-cluster-node-A:4222,nats://nats-cluster-node-B:4222,nats://nats-cluster-node-C:4222 -l ./logs/nats-node-B.log -DV"
    networks:
      - nats-streaming-example

  nats-streaming-node-C:
    image: nats-streaming:latest
    restart: always
    expose:
      - "4222"
      - "6222"
    ports:
      - "4222"
      - "6223:6223"
    hostname: "nats-node-C"
    volumes:
      - "./logs:/logs"
      - "./nats/shareddatastore-C:/nats/shareddatastore-C"
      - "./nats/cluster/nats-cluster-node-C:/cluster/nats-cluster-node-C"
    command: "-p 4222 -store file -dir /nats/shareddatastore-C -clustered -cluster_id swarm -cluster_node_id node-C -cluster_log_path /cluster/nats-cluster-node-C -cluster_peers node-A,node-B,node-C -nats_server nats://nats-cluster-node-A:4222,nats://nats-cluster-node-B:4222,nats://nats-cluster-node-C:4222 -l ./logs/nats-node-C.log -DV"
    networks:
      - nats-streaming-example

  natsnlogconsumer:
    image: ${DOCKER_REGISTRY-}natsnlogconsumer
    build:
      context: .
      dockerfile: NatsNlogConsumer/Dockerfile

  natsnlogexample:
    image: ${DOCKER_REGISTRY-}natsnlogexample
    build:
      context: .
      dockerfile: NatsNlogExample/Dockerfile